### ISSUE TITLE
hyperloglog functionality support 

### ISSUE THREAD

**Issue by knight1128** [bwlewis/rredis#30]
Hi~

Could you make hyperloglog redis command  like pfcount command ?

**Comment by knight1128** [comment]
I have tried 'redisCmd("PFCOUNT" ..)' function. It's well working!

**Comment by bwlewis** [comment]
Great. redisCmd comes in handy for new redis features. I'll leave this open and mark it as a new feature desired for next version...

**Comment by knight1128** [comment]
Thank you @bwlewis !

The redisCmd("PFCOUNT") is taken 0.04s.
I tried to call millions of redisCmd command, It takes 0.04 * number of milloins of the call.

So, could you make hyperloglog multiple-get function like mget?

**Comment by bwlewis** [comment]
There isn't a low-level redis mget for pfadd/pfcount/pfmerge, so I can't really add that (it doesn't exist).

However, I think you can achieve what your looking for with pipelining and/or transactions. Try using pipelining (aka non-blocking mode) and/or transactions. See:

```r
?redisSetBlocking
?redisMulti
```

**Comment by bwlewis** [comment]
Sorry for the long latency, I finally got these functions into the package. You can try it out direct from GitHub with:

```r
devtools::install_github("bwlewis/rredis")
```
See the `redisPfadd`, `redisPfcount`, `redisPfmerge` functions.

Should be on CRAN in a week or two depending on some other work on the package.

**Comment by knight1128** [comment]
@bwlewis Thank you for your serving. I can use pfcount/pfadd/pfmerge for you.
