### ISSUE TITLE
redisLPush(key, value, ...)

### ISSUE THREAD

**Issue by ersidam** [bwlewis/rredis#31]
function is not adding correnct value to list, it can be a character encoding problem

**Comment by bwlewis** [comment]
Can you provide a reproducible example?

**Comment by ersidam** [comment]
I'm reading some json string and make some calculation... Then I need to return a json string but when working with redisLPush, it returns some value like in screenshoot.
firstly I think problem in jsonlite so I send just text string, there is no change in result.

library("rredis");
library("jsonlite");
redisConnect(host = "192.168.1.25",port = 6379);
while(TRUE){
  req <- redisRPop("request");
  if(!is.null(req)){
    
    data <- fromJSON(req);
  	#calculations
        #print(data);
    
    res <- toJSON(data);
    redisLPush(key = 'response',value = res );
  }
}

![ekran alintisi](https://cloud.githubusercontent.com/assets/5265318/9689810/2a043cec-5341-11e5-9bcd-590d3ae0f1c2.PNG)

**Comment by bwlewis** [comment]
See the 'raw' options to send un-serialized data to Redis (also
discussed in the vignette).

The default sends serialized R objects.

**Comment by ersidam** [comment]
applying charToRaw() function  before sending data tp redis is a solution  thanks

**Comment by bwlewis** [comment]
Great, glad that works. I'm trying to get doRedis updated on CRAN soon, but still have some work to do on the package... Closing this issue now.
