### ISSUE TITLE
Multiple databases?

### ISSUE THREAD

**Issue by Peder2911** [bwlewis/rredis#41]
Hello!
Wanted to use this, but i need to be able to specify which database to connect to.
Seems like this is currently not possible.
P

**Comment by Peder2911** [comment]
Never mind, found redux.

**Comment by bwlewis** [comment]
I'mglad you found redux -- everybody needs to switch to that.

FYI my intermediate plan when I can get to it will be to have one more
version of rredis that is itself based on redux to help any remaining
users transition over to that.
