### ISSUE TITLE
redisHIncrByFloat seems to be calling the wrong Redis function

### ISSUE THREAD

**Issue by davidlub** [bwlewis/rredis#42]
Hi,

> redisHIncrByFloat
function (key, field, value, ...) 
{
    .redisCmd(.raw("**HINCRBY**"), .raw(key), .raw(field), 
        .raw(as.character(value)), ...)
}

It  should be calling **HINCRBYFLOAT**.

Thanks for your work on Rredis - we use it extensively.
David

**Comment by bwlewis** [comment]
Hi David,

  Is it possible for you to transition to using the redux package instead? I had though most use of rredis was done by now and am planning on removing it from CRAN soon.

Best,

Bryan

**Comment by davidlub** [comment]
Hi,

Thanks for the reply and sorry I didn't see it for so long.  We have move the project over to redux, still rredis was very useful to us and thanks a lot for your time in creating it. 

David
